services:
  scraper:
    build:
      context: ../..
      dockerfile: services/scraper/Dockerfile
    depends_on:
      create-topics:
        condition: service_completed_successfully
    ports:
      - "8080:3000"
  core-api:
    build:
      context: ../..
      dockerfile: services/core-api/Dockerfile
    depends_on:
      create-topics:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=development
      - PORT=3000
      - KAFKA_BROKER=kafka:9092
      - LOG_LEVEL=info
    ports:
      - "8081:1234"
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 3
    logging:
      driver: json-file