# generated by datamodel-codegen:
#   filename:  events
#   timestamp: 2026-07-07T13:17:38+00:00

from .ScrapeRequestedEvent import ScrapeRequestedEvent
from .RecipeParsedEvent import RecipeParsedEvent
