# generated by datamodel-codegen:
#   filename:  RecipeParsedEvent.json
#   timestamp: 2026-07-12T13:40:08+00:00

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, PositiveFloat, confloat


class Header(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: UUID
    timestamp: str


class Ingredient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    quantity: float
    unit: str | None = None


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    url: str
    site_name: str
    description: str
    category: str
    cuisine: str
    image_url: str
    servings: str
    nutrients: dict[str, Any] = Field(..., max_length=0)
    prep_time_min: PositiveFloat
    cook_time_min: PositiveFloat
    ratings: confloat(le=5.0, gt=0.0)
    ratings_count: float
    steps: list[str]
    ingredients: list[Ingredient]


class RecipeParsedEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    header: Header
    event_type: Literal['recipe-parsed']
    payload: Payload
