# generated by datamodel-codegen:
#   filename:  RecipeParsedEvent.json
#   timestamp: 2026-07-07T15:15:45+00:00

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint


class Header(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: UUID
    timestamp: str


class Duration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    days: conint(le=9007199254740991, gt=0)
    hours: conint(ge=-9007199254740991, lt=24)
    minutes: conint(lt=60, gt=0)


class Ingredient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    quantity: float
    unit: str | None = None


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    url: str
    description: str
    servings: str
    duration: Duration
    steps: list[str]
    ingredients: list[Ingredient]


class RecipeParsedEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    header: Header
    event_type: Literal['recipe-parsed']
    payload: Payload
