# generated by datamodel-codegen:
#   filename:  ScrapeRequestedEvent.json
#   timestamp: 2026-07-12T13:40:09+00:00

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Header(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: UUID
    timestamp: str


class ScrapeRequestedEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    header: Header
    event_type: Literal['scrape-requested']
    url: str
